CATEGORIES:
  Assemblies:
    Printed-Circuit Board Assembly: null
    Product: null
  Capacitors:
    Aluminium: null
    Ceramic:
      '0402': null
      '0603': null
      '0805': null
    Polymer: null
    Super Capacitors: null
    Tantalum: null
  Circuit Protections:
    Fuses: null
    PTC: null
    TVS: null
  Connectors:
    Battery: null
    Board-to-Board: null
    Coaxial: null
    FPC: null
    Header: null
    Interface: null
  Crystals and Oscillators:
    Crystals: null
    Oscillators: null
  Diodes:
    LED: null
    Schottky: null
    Standard: null
    Zener: null
  Inductors:
    Ferrite Bead: null
    Power: null
  Integrated Circuits:
    Interface: null
    Logic: null
    Memory: null
    Microcontroller: null
    Sensor: null
  Mechanicals:
    Nuts: null
    Screws: null
    Standoff: null
    Switch: null
  Miscellaneous:
    Batteries: null
  Modules: null
  Power Management:
    Boost: null
    Buck: null
    LDO: null
    PMIC: null
  Printed-Circuit Boards: null
  RF:
    Antenna: null
    Chipset: null
    Filter: null
    Shield: null
  Resistors:
    NTC: null
    Potentiometers: null
    Surface Mount: null
    Through Hole: null
  Transistors:
    Load Switches: null
    N-Channel FET: null
    NPN: null
    P-Channel FET: null
    PNP: null
CODES:
  Assemblies: PCA
  Capacitors: CAP
  Circuit Protections: PRO
  Connectors: CON
  Crystals and Oscillators: CLK
  Diodes: DIO
  Inductors: IND
  Integrated Circuits: ICS
  Mechanicals: MEC
  Miscellaneous: MIS
  Modules: MOD
  Power Management: PWR
  Printed-Circuit Boards: PCB
  RF: RFC
  Resistors: RES
  Transistors: TRA